# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - master
      - use-rstantools
  pull_request:
    branches:
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.rstan }} RStan - ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: macOS-latest, r: 'devel' }
          - { os: macOS-latest, r: 'release' }
          - { os: macOS-latest, r: 'oldrel' }
          - { os: windows-latest, r: 'devel' }
          - { os: windows-latest, r: 'release' }
          - { os: windows-latest, r: 'oldrel' }
          - { os: ubuntu-latest, r: 'devel' }
          - { os: ubuntu-latest, r: 'release' }
          - { os: ubuntu-latest, r: 'oldrel' }
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      TESTTHAT_CPUS: 4

    steps:
      - uses: n1hility/cancel-previous-runs@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master'"

      - uses: actions/checkout@main

      - uses: r-lib/actions/setup-r@v2-branch
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@v2-branch
      - uses: r-lib/actions/setup-r-dependencies@v2-branch
        with:
          extra-packages: any::rcmdcheck any::betareg any::HSAUR3 any::biglm any::gamm4 any::V8
      - uses: r-lib/actions/check-r-package@v2-branch
